let bookes = [
  {
    ISBN: 1,
    name: "Book1",
    category: "cetegory1",
    image: "images/1.jpg",
    pages: 400,
    author: "auther1",
    price: 120,
  },
  {
    ISBN: 2,
    name: "Book2",
    category: "cetegory1",
    image: "images/2.jpg",
    pages: 200,
    author: "auther2",
    price: 120,
  },
  {
    ISBN: 3,
    name: "Book3",
    category: "cetegory1",
    image: "images/3.jpg",
    pages: 40,
    author: "auther3",
    price: 120,
  },
  {
    ISBN: 4,
    name: "Book1",
    category: "cetegory1",
    image: "images/4.jpg",
    pages: 30,
    author: "auther4",
    price: 120,
  },
  {
    ISBN: 5,
    name: "Book1",
    category: "cetegory1",
    image: "images/5.jpg",
    pages: 400,
    author: "auther5",
    price: 120,
  },
  {
    ISBN: 6,
    name: "Book1",
    category: "cetegory1",
    image: "images/6.jpg",
    pages: 200,
    author: "auther6",
    price: 120,
  },
];
